# Generated by Django 5.1.3 on 2025-01-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_player_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='score',
            new_name='sco_re',
        ),
    ]
