# Generated by Django 5.1.3 on 2025-01-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_score_player_sco_re'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sco_re',
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
