# Generated by Django 5.1.3 on 2024-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id_42'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id_42',
        ),
        migrations.AddField(
            model_name='customuser',
            name='intra_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
