# Generated by Django 5.1.3 on 2024-11-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='intra_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profil_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
