# Generated by Django 5.1.3 on 2025-01-17 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournament_players', through='authe.PlayerEntry', to=settings.AUTH_USER_MODEL),
        ),
    ]
