# Generated by Django 5.1.3 on 2024-12-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_connect',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
