# Generated by Django 5.1.3 on 2025-01-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_customuser_is_online_customuser_last_connect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_connect',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
