# Generated by Django 5.1.3 on 2025-01-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0005_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
