# Generated by Django 5.1.3 on 2025-01-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0005_relationsships'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelationsShips',
        ),
    ]
