# Generated by Django 5.1.3 on 2025-01-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0006_alter_tournament_game_alter_tournament_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profil_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
