# Generated by Django 5.1.3 on 2025-01-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0006_alter_tournament_game_alter_tournament_id'),
        ('authe', '0006_delete_relationsships'),
    ]

    operations = [
    ]
