# Generated by Django 5.1.3 on 2025-01-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0007_alter_customuser_profil_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='player',
            new_name='players',
        ),
    ]
