# Generated by Django 5.1.3 on 2025-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_relationship_delete_relationsships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relations',
            field=models.CharField(choices=[('none', 'None'), ('friend', 'Friend'), ('blocked', 'Blocked')], default='none'),
        ),
    ]
